Feature/scrimmage
FRC1732/2022-Competition pull request #87
Opened 2022-03-19 20:46 UTC by dkScammer

literally shoots from anywhere

2022-03-20 16:25 UTC, rguinn2338 commented on src/main/java/frc/robot/Constants.java
> +    public static final double COMPETITION_BACK_RIGHT_MODULE_STEER_OFFSET = -Math.toRadians(-39.16 - 2.2);
- [ ] condense these into single numbers instead of expressions

2022-03-20 16:27 UTC, rguinn2338 commented on src/main/java/frc/robot/RobotContainer.java
> +  // private final SlewRateLimiter m_rotLimiter = new SlewRateLimiter(3);
- [ ] Remove these entirely, simply uncommenting won't give us the functionality back

2022-03-20 16:29 UTC, rguinn2338 commented on src/main/java/frc/robot/RobotContainer.java
> +      //}
- [ ] Remove commented code

2022-03-20 16:34 UTC, rguinn2338 commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    if (distance > 9) {
- [ ] Replace 8.5 and 9 with constants: HOOD_CHANGE_DISTANCE = 8.75 and HOOD_CHANGE_DISTANCE_THRESHOLD = .25

2022-03-21 18:05 UTC, borkae requested changes

2022-03-21 23:44 UTC, closed without merging